

== Om dokumentet
Del 1 er skrevet av Difi ved mailto:heather.broomfield@difi.no[Heather Broomfield] og mailto:oystein.asnes@difi.no[Øystein Åsnes]. Bidragsytere: Øyvind Grinde, Livar Bergheim og Marta Kari Schawlann.

Status for de 5 sektorene (Del 2), er beskrevet av ansvarlig departement for hvert område. Kontaktpersoner i departementene:
_kart- og eiendomsdata_; Kari Strande (Kommunal- og moderniseringsdepartementet) _transportsektoren_; Ida Monclair (Samferdelsdepartementet),  _statlige utgifter_; Astri Tverstøl (Finansdepartementet), _forskning_; Hanne Monclair (Kunnskapsdepartementet), _kultur_; Bjørn Olav Tveit (Kulturdepartementet).

Dokumentet må ses i sammenheng med arbeidet som ble varslet i  https://www.regjeringen.no/no/dokumenter/meld.-st.-27-20152016/id2483795/[Meld. St. 27 (2015-2016) Digital agenda for Norge] der de nevnte områdene skal utarbeide strategier for økt tilgjengeliggjøring av offentlige data. Strategiene blir lenket etterhvert som de er ferdigstilt:

.Oversikt over de ulike strategiene
|===
|Område | Lenke til strategi | Status

|Kart- og eiendomsdata
|https://www.regjeringen.no/contentassets/6e470654c95d411e8b1925849ec4918d/kmd_alt_skjer_et_sted_geodatastrategi.pdf[Alt skjer et sted
Nasjonal geodatastrategi fram mot 2025 (PDF)]
|Ferdig

|Forskning
|https://www.regjeringen.no/id2582412/[Nasjonal strategi for tilgjengeliggjøring og deling av forskningsdata]
|Ferdig

|Kultur
|https://www.regjeringen.no/id2576038/[Kulturdepartementets strategi for åpne data]
|Ferdig

|Transport
|https://www.regjeringen.no/no/dokumenter/strategi-for-tilgjengeliggjoring-av-offentlige-data--samferdselssektoren/id2598229/[Strategi for tilgjengeliggjøring av offentlige data – samferdselssektoren]
|Ferdig

|Statlige utgifter
|(ikke tilgjengelig)
|(ikke tilgjengelig)

|===


Dokumentet blir oppdatert ved behov.
Sist endret: 20.12.2018

== Innledning
Det offentlige produserer store mengder data i sin saksbehandling og myndighetsutøvelse. Tilgang på data, og kunnskap om hvordan de kan brukes, er i økende grad en forutsetning for å kunne ta beslutninger, utvikle nye tjenester og å utøve et åpent og opplyst demokrati. Data blir i økende grad brukt i andre sammenhenger, til andre formål og av andre aktører enn det som var utgangspunktet da informasjonen ble skapt.

Økt tilgang på offentlige data og kunnskap om hvordan de kan brukes, er viktig for å legge til rette for størst mulig verdiskapning i en stadig mer datadrevet økonomi. Regjeringen har derfor valgt ut fem sektorer der det skal lages strategier (og eventuelle handlingsplaner) for økt tilgjengeliggjøring av offentlige data. Som et ledd i dette arbeidet har Difi fått i oppdrag av Kommunal- og moderniseringsdepartementet (KMD) å publisere et kunnskapsgrunnlag som skal gi oversikt over nå-situasjonen og en beskrivelse av kjente utfordringer for områdene _statlige utgifter, transport, kart- og eiendomsdata, kultur og forskning_. Formålet er å bidra til å identifisere mulige tiltak i form av prioriteringer, beslutninger og avklaringer for å nå målet om økt tilgang på data fra de fem sektorene.

Dokumentet er basert på innspill fra sektorene, kommunikasjon med brukere, internasjonale indekser, ulike strategier og rapporter samt Difis fagkompetanse. Del 1 begynner med en oppsummering av Norges status internasjonalt. Dette blir etterfulgt av en status for åpne data i Norge og deretter en beskrivelse av felles utfordringer og suksessfaktorer som vi har identifisert i prosessen. De sektorvise beskrivelsene av nå-situasjonen utgjør del 2.

== Norges og sektorenes status internasjonalt

Kartlegging av status for åpne data internasjonalt er forholdsvis modent og gjennomføres systematisk. Det to viktigste indeksene, http://index.okfn.org/[Global Open Data Index] og http://opendatabarometer.org/[Open Data Barometer], har Norge på henholdsvis en 10.- og 17.- plass i 2015.  Dette er ned fra en topp 5-plassering i begge indeksene i 2013. https://www.europeandataportal.eu/sites/default/files/country-factsheet_norway.pdf[EUs egne kartleggingsrapporter] viser et lignende mønster for Norge. Selv om Norge blir sett på som en “fast tracker”, er vi ikke blant gruppen av land som er trendsettere.

*Kart- og eiendomsdata* er utvilsomt en av de mest etterspurte datasettene internasjonalt. EUs https://ec.europa.eu/digital-single-market/en/news/commission-notice-guidelines-recommended-standard-licences-datasets-and-charging-re-use[Guidelines on recommended standard licence, datasets and charging for the re-use of documents] og http://opendatacharter.net/[The International Open Data Charter] trekker frem kart- og eiendomsdata som spesielt verdifulle og at tilgjengeliggjøring av disse dataene må prioriteres.  Begge indeksene som er nevnt i innledningen, har kart- og eiendomsdata som indikatorer i sine rangeringer.  Norge skårer høyt på kartdata, men svært lavt på tilgang til eiendomsdata. Her bør det være handlingsrom til å gjøre mer data tilgjengelig også i Norge.

Det finnes lite sammenlignbare tall for *åpne kulturdata* i Norge og kultursektoren i Europa. Likevel har vi tall som indikerer at situasjonen er noe bedre i Norge og Norden enn i Europa for øvrig. Større åpenhet og transparens generelt i forvaltningen kan ha bidratt positivt også i kultursektoren. Norge er den tredje største bidragsyteren til Europeana (regnet i totalt antall etter Nederland og Tyskland) og den desidert største bidragsyteren regnet per innbygger. Det Europeana-eide prosjektet http://pro.europeana.eu/structure/enumerate[Enumerate] leverte tall i sin rapport http://www.enumerate.eu/fileadmin/ENUMERATE/documents/ENUMERATE-Digitisation-Survey-2014.pdf[Survey Report on Digitisation in European Cultural Heritage Institutions 2014] som viser at kulturarvssektoren også på andre relaterte områder står seg godt i en sammenlikning med Europa.

Tilgjengeliggjøring av *forskningsdata* er et viktig tema også globalt, og spesielt EU har mange aktiviteter som skal støtte opp under bedre tilgang, bruk og deling av forskningsdata. Internasjonal status er ikke kartlagt, men sentrale internasjonale føringer viser en økt satsning på tilgjengeliggjøring av data. Her er noen sentrale aktiviteter på området:

 * EU har vedtatt ambisiøse rådskonklusjoner om åpen forskning
 * Europakommisjonen har besluttet at alle data som genereres gjennom Horisont 2020 skal være åpne som standard
 * EUs planer om en https://ec.europa.eu/research/openscience/index.cfm?pg=open-science-cloud[European Open Science Cloud] (EOSC).
 * OECD Global Science Forums satsninger på åpne data

I tillegg har Frankrike vedtatt en egen lov om åpen tilgang til forskningsresultater

Data om *offentlige utgifter* er prioriterte datasett i internasjonale indekser og retningslinjer knyttet til åpne data, som for eksempel EUs https://ec.europa.eu/digital-single-market/en/news/commission-notice-guidelines-recommended-standard-licences-datasets-and-charging-re-use[Guidelines on recommended standard licence, datasets and charging for the re-use of documents] og http://opendatacharter.net/[The International Open Data Charter].

Data om offentlige utgifter er også sentrale indikatorer både i Global Open Data Index og Open Data Barometer. Norge skårer henholdsvis 10 og 5 prosent (av 100 mulige) på disse indeksene på området. Begge indeksene har tilgang til utgiftsdata på transaksjonsnivå som kriterium.

Det er mye aktivitet i Europa knyttet til transportsektoren og høy etterspørsel etter *transportdata* internasjonalt, spesielt sanntidsdata. The Open Data Barometer er den eneste indeksen som har transportdata som måleindikator, og Norge oppnår her en score på 80%  (av 100 mulige) for tilgang til rutetabeller for kollektivtransport.

== Status for åpne data i Norge
Tjenesten https://data.norge.no[Data.norge.no], med en nasjonal katalog over åpne data fra det offentlige, ble lansert i 2011. Pr. 31.12.16 er det rundt 6700 individuelle datasett fra 83 statlige og kommunale virksomheter i katalogen. En stor bidragsyter er SSB sin statistikkbank med over 5000 tabeller.

Per i dag er det ingen lovpålagt plikt til å legge data ut for viderebruk. Offentleglova har imidlertid bestemmelser om hvordan offentlige data for viderebruk skal tilgjengeliggjøres.

I 2011 ga regjeringen en fellesføring til alle statlige virksomheter om å åpne opp data, med fokus på datasett som var enkle å gjøre tilgjengelige. Siden den gang har føringer blitt gitt i https://www.regjeringen.no/no/dokumenter/digitaliseringsrundskrivet/id2522147/[Digitaliseringsrundskrivet]. Digitaliseringsrundskrivet sier at virksomheten skal “gjøre egnet informasjon tilgjengelig i maskinlesbare formater, fortrinnsvis gjennom API'er” og at det skal legges til rette for dette ved etablering av nye eller oppgradering av eksisterende fagsystemet eller digitale tjenester.

I tillegg er det etablert noen virkemidler for å fremme tilgang til (og viderebruk av) offentlige data:

 * Tjenesten https://data.norge.no[Data.norge.no],  som er en nasjonal katalog over datasett som er tilgjengelig for viderebruk.
 * Tjeneste for distribusjon av data (https://data.norge.no/datahotellet[Datahotellet]).
 * https://www.regjeringen.no/no/id2536870/[Retningslinjer ved viderebruk av offentlige data.]
 * https://data.norge.no/document/del-og-skap-verdier-veileder-i-tilgjengeliggj%C3%B8ring-av-offentlige-data[Veileder i tilgjengeliggjøring av åpne data]
 * Utvikling av en https://data.norge.no/nlod/no[norsk lisens for offentlige data (NLOD)]
 * Ulike konkurranser, hackathons, der offentlige data er stilt til rådighet for aktuelle utviklingsmiljø.

== Felles utfordringer og suksessfaktorer

Noen utfordringer og kritiske suksessfaktorer som beskrives av sektorene, er (eller burde være) felles for alle, og felles tiltak kan være hensiktsmessig. En felles forståelse av disse faktorene er uansett viktig. På grunnlag av sektorenes egne beskrivelser av nå-situasjonen peker vi her på noen problemstillinger vi mener er sentrale.

=== Lite kunnskap om bruk og effekter

Verdier skapes først når data blir tatt i bruk. Etter 5 år med https://data.norge.no[Data.norge.no] er nå mange datasett med høy verdi gjort tilgjengelig, og det er behov for å måle effektene. Dette er en fase som mange land er inne i. Kunnskapen om effektene er viktig for å stimulere til mer tilgjengeliggjøring. Manglende kunnskap om effekter kan derfor sees som et hinder for tilgjengeliggjøring.

Åpne data blir som regel publisert åpent, uten krav til å registrere seg for å få tilgang, og det er heller ikke mulig å stille krav til at brukerne må rapportere om hva datasettene blir brukte til. Selv om vi har god oversikt over hvilke datasett som er tilgjengelig, har vi altså begrenset oversikt over hva de brukes til.

https://data.norge.no[Data.norge.no] har en katalog over apper og tjenester som bruker åpne data. Brukerne kan selv logge inn og registrere nye oppføringer, og til nå er det nærmere https://data.norge.no/app[70 oppføringer i registeret]. Vi opplever at det er en viss terskel for å registrere produkter i registeret. Kartverket og Kulturrådet har egne oversikter over applikasjoner og tjenester som bruker henholdsvis kart- og kulturdata.

I tillegg til relativt synlige effekter i form av mobilapplikasjoner og tjenester inngår åpne data også i tjenestekjeder og i eksisterende arbeidsprosesser både i og utenfor offentlig sektor. Eksempler her er vasking av interne register mot enhetsregisteret og bruk av åpne kartdata i fagsystemer. Åpne data fra det offentlige bidrar dermed til mer effektive arbeidsprosessser. Men de samfunnsøkonomiske gevinstene er utfordrende å både synliggjøre og å måle.

Man kan se på statistikk for antall nedlastinger av datasett og på hvor mange spørringer som blir gjort mot maskingrensesnitt (API-er) som leverer ut data, dersom denne informasjonen er tilgjengelig. Ettersom https://data.norge.no[Data.norge.no] bare inneholder beskrivelser av data (ikke selve datasettene), er dette informasjon som per i dag ikke samles inn eller benyttes som måleindikator av Difi.

Alle de fem områdene har gjort data tilgjengelig, men vi vet i dag lite om hvilke tjenester og prosesser datasettene inngår i, og hvilke effekter dette gir. En antatt sideeffekt ved økt bruk er at også datakvaliteten forventes å øke som et resultat av flere tilbakemeldinger fra brukerne. Utvikling av gode måleindikatorer for å måle bruk av data og effektene dette gir, er en utfordring som mange land prøver å løse.

=== Økosystemet - samspillet mellom offentlig og privat sektor

Erkjennelsen av viktigheten av et økosystem og avhengighetsforhold mellom sektorene og deres interessenter er viktig for å lykkes. Et fungerende økosystem er avgjørende for innovasjon, og offentlige virksomheter må også se “eksterne” som viktige dataleverandører. Offentlig sektor må være utadvendt -  en kan ikke forvente at aktuelle brukere ser potensialet eller finner dataene uten aktiv formidling fra forvaltningens side. Et godt samspill  +
og samarbeid om deling, utvikling og innovasjon mellom aktørene i offentlig og privat sektor bør derfor være et uttalt mål i strategier som utformes.

Mobilisering av publikum som produsenter av data – såkalt nettdugnad (crowdsourcing) – representerer et stort potensial for kostnadseffektiv datainnsamling. Sammen med tjenesteytere og brukere kan de etablere effektive «dataøkosystemer».

Det kan være utfordrende for dataforvaltere å vite hva som bør prioriteres først, når det ikke foreligger konkrete forespørsler i markedet. Samtidig er det krevende for potensielle brukere (både internt i offentlig sektor og for næringsliv og sivilsamfunn) å etterspørre data på en konkret måte uten kjennskap til hvilke data offentlig sektor forvalter. Virksomheten bør derfor vedlikeholde og publisere en oversikt over de viktigste dataene de forvalter slik at tilgjengeliggjøring kan prioriteres ut fra brukernes behov.

Flere av sektorene peker på at økosystemet er viktig, og Kart- og eiendomssektoren er spesielt tydelige på dette behovet. De har uttrykt følgende som en av sine hovedmål i https://www.geonorge.no/globalassets/geonorge2/ny-nasjonal-geodatastrategi/geodatastrategi-utkast_140217.pdf[høringsutkastet til strategi]:

[quote, Alt skjer et sted - Forslag til nasjonal geodatastrategi]
Mål 3: Et velfungerende samspill om forvaltning, deling, utvikling og innovasjon mellom aktørene i offentlig og privat sektor_”

De har også målsetninger om å videreutvikle felles arenaer for offentlig-privat samarbeid og å skape aktive miljøer og fellestiltak for innovasjon og FoU. Strategien er også opptatt av mobilisering av publikum som produsenter av data.

Kultursektoren trekker fram behovet for å stimulere til bruk og påpeker at man ikke kan forvente at potensielle brukere ser mulighetene eller finner dataene uten aktiv formidling fra sektorens side.

Det er nødvendig å “pleie” økosystemet for å maksimere verdien av offentlige data og etablere fungerende markedsplasser for åpne data. Selv om sektorene har egne økosystemer, er det trolig store muligheter knyttet til horisontale tiltak ettersom mange innovasjoner trolig vil være basert på flere kilder og data fra ulike sektorer.

=== Uklarheter rundt anledning til å dele data

En annen utfordring for flere er problemstillinger knyttet til eierskap til data. Når data produseres av flere aktører (ved for eksempel “nettdugnad”, eller når data samles i sentrale løsninger) er det ofte uklarheter rundt hvem som kan dele data eller hvilke aktører det må avklares med. Ettersom det er forskjellige praksis og uklarheter, oppstår det en del paradokser rundt distribusjon av data fra sentrale løsninger. Her er noen eksempler:*)

 * KS leverer ikke ut data fra sitt http://www.ks.no/fagomrader/Arbeidsgiver/analyse-og-statistikk/innsamling-av-data/datainnsamling-til-pai-registeret-2016/[PAI-register]. KS er en interesseorganisasjon og dermed kan heller ikke Offentleglova anvendes for å hente ut data sentralt, selv om akkurat de samme opplysningene er underlagt Offentleglova i hver enkelt kommune. Man må altså be om innsyn fra hver enkelt kommune, istedenfor å få det gjennom et sentralt register. Dette er en lite hensiktsmessig bruk av offentlige ressurser.

 * Direktoratet for økonomistyring (DFØ) leverer regnskapstjenester til en rekke offentlige virksomheter. Offentlige eller private aktører må henvende seg til den virksomheten som eier regnskapsinformasjonen for å få tilgang til data, selv om informasjonen i praksis blir forvaltet i et sentralt system av en offentlig virksomhet.

 * https://kartkatalog.geonorge.no/metadata/geovekst/felles-kartdatabase-fkb/0e90ca71-6a02-4036-bd94-f219fe64645f[Felles kartdatabase] (FKB) er detaljerte kartdata som kommunene leverer via Geovekst-samarbeidet og som blir forvaltet av Kartverket. Selv om en sentralisert løsning finnes, har ikke Kartverket mandat til å distribuere dette som åpne data. På grunn av kommunenes forpliktelser gjennom Geovekst-samarbeidet har heller ikke kommunene anledning til å tilby egne FKB-data som åpne data. Finansiering av FKB-data er blant dilemmaene som omtales i forslaget til ny geodatastrategi.

 * Mange private og ideelle organisasjoner får i oppdrag å samle inn og analysere data på vegne av det offentlige. Disse dataene er svært ofte ikke tilgjengelige som åpne data. Noen ganger er de heller ikke tilgjengelige for oppdragsgiver selv.

 * Ved privatisering av funksjoner og overføring av forvaltningsansvar til stiftelser og virksomheter som er unntatt offentlighet, er det viktig at behovet for tilgang til data ivaretas. Eksempler på data som vi regner som offentlige, men som juridisk sett er/blir unntatt offentlighet som følge av privatisering eller overføring av forvaltningsansvar, er flere.

*) Merk at ikke alle eksemplene er relevante for de fem områdene https://www.regjeringen.no/no/dokumenter/meld.-st.-27-20152016/id2483795/sec3#KAP14[som er omtalt i Digital Agenda] (Kap 14.2.2). De illustrerer likefullt problemstillingen på en god måte.

=== Behov for kompetanse om deling og bruk av data

For å utnytte mulighetene må brukerne ha kunnskap om hvordan dataene kan utnyttes. Mye av innsatsen har til nå blitt rettet mot å etablere bevissthet rundt _deling_ av data. Dette må utvides til også å omfatte utvikling av kunnskap knyttet til _bruk_ av data. Samtidig bør offentlig sektor i større grad se sin rolle som konsumenter av åpne data fra det offentlige i en stadig mer datadrevet forvaltning, og bygge opp nødvendig kompetanse til å utnytte dette.

Kart- og eiendomssektoren framstår som moden når det gjelder kompetanse på deling av data. De er samtidig tydelige på behovet for kompetansebygging på brukersiden og har satt seg som mål at kompetanse om geografisk informasjon og tilhørende løsninger skal være utbredt:

[quote, Alt skjer et sted - Forslag til nasjonal geodatastrategi]
[Delmål 3.5] Kompetanse om geografisk informasjon og tilhørende løsninger er utbredt
Kunnskap om geografisk informasjon og geografiske metoder er nødvendig for full utnyttelse av potensialet og realiseringen av denne strategien […] Det skal utvikles en langsiktig tiltakspakke som bidrar til å tilføre nødvendig kompetanse om bruk og utvikling av brukerløsninger basert på geografisk informasjon – og som kan fremme innovasjon og verdiskapning i samfunnet.

Også uformell kompetanseutvikling er viktig. Deler av kultursektoren har jobbet målrettet for å utvikle brukermiljø og kompetanse på brukersiden gjennom workshops, seminar og hackathons.

I transportsektoren er det naturlig å trekke frem Statens vegvesens innsats med å involvere brukerne av Nasjonal vegdatabanks (NVDB) tekniske grensesnitt, mellom annet gjennom bloggen http://vegdata.no[vegdata.no].

Behovet for kompetanse om deling og bruk av data vil bare øke i årene som kommer. Dette gjelder både i offentlig og privat sektor.

=== Teknologi, infrastruktur og rammeverk

Flere sektorer peker på behovet for å etablere bærekraftige infrastrukturer. Også brukerne etterlyser i økende grad forutsigbarheit og langsiktighet knyttet til tilgang til data. Løsningene som etableres for lagring og distribusjon av data bør derfor være langsiktige.

Her ligger det muligheter for samarbeid på tvers, både på nasjonalt og internasjonalt nivå, og en må stille spørsmål ved om alle fagområder og sektorer har behov for egne infrastrukturer eller om etablering av felles løsninger eller komponenter er hensiktsmessig. Felles spesifikasjoner og standarder blir uansett viktig for å kunne utveksle data og metadata på tvers av sektorer, samtidig som domenespesifikke og internasjonale behov må ivaretas. Difis https://www.difi.no/fagomrader-og-tjenester/digitalisering-og-samordning/nasjonal-arkitektur/informasjonsforvaltning[Fellesoffentlig rammeverk for informasjonsforvaltning] er relevant her.

https://www.geonorge.no/[Geonorge ]er eksempel på en eksisterende infrastruktur som kan være relevant for flere sektorer. Kartdata er ikke et eget område eller en egen sektor, men heller en egenskap ved dataene (de er knyttet til et sted). Deler av forskningssektoren har behov for mange av de løsningene som utvikles og forvaltes i kart- og eiendomssektoren, og et tettere samarbeid bør vurderes nærmere.

Samtidig bør etablerte domenespesifikke infrastrukturer sikres langsiktighet, enten som fellesløsninger eller som løst koblede tjenester basert på størst mulig grad av felles standarder og spesifikasjoner. For eksempel har Kulturrådet lykkes godt med å samle en rekke institusjoner rundt løsningene http://norvegiana.no/[Norvegiana] / http://www.europeana.eu/portal/no[Europeana] og http://kulturnav.org/[Kulturnav]. Samtidig mangler sentrale nasjonale institusjoner innen kulturfeltet i disse løsningene.

Ulike økosystemer trekker inn mer data fra forskjellige kilder, som vil føre til behov for tettere koblinger mellom infrastrukturer. Brukerne konfronteres i dag med ulike plattformer og fellesløsninger innen beslektede sektorer og fagdomener. For eksempel er det behov for gode koblinger mellom https://www.geonorge.no/[Geonorge] og https://data.norge.no[Data.norge.no]. En løsning for dette er under utvikling.

I det videre arbeidet med etablering av infrastrukturer for deling og utveksling av data og metadata bør felleskomponenter, løsninger og standarder også _på tvers_ av sektorer etableres der det er hensiktsmessig. Fellesløsninger og teknologi som velges må sikres langsiktighet og understøtte en effektiv oppgaveløsning og åpne for nye bruksmuligheter i samfunnet.

Behovet for felles vokabular og autoriserte registre gjelder for flere sektorer. Entydig referering til informasjon som forvaltes i en annen virksomhet (og i en annen sektor) stiller derfor krav til hvordan autoritetsregistre og kodeverk gjøres tilgjengelig. Behovene oppstår gjerne i andre sektorer og virksomheter enn der informasjonen forvaltes og prioriteringene gjøres. Et eksempel er kultursektorens behov for å knytte informasjon til steder ved hjelp av URI-er i lenkede data-miljøer.

Det er uklart hvilke autoritetsregistre sektorene har behov for, hvilke som skal brukes, hvem som skal ha ansvar for å etablere og/eller ivareta disse registrene over tid, og hvordan de skal gjøres tilgjengelige. Ansvar og funksjoner bør forankres i miljøer og infrastrukturer som kan sikre nødvendig stabilitet og langsiktighet.

=== Lovverk og politiske føringer
Med en rask teknologiutvikling er det en fare for at lovverk og strukturer ikke er tilpasset de muligheter og behov samfunnet faktisk har. På den annen side kan lov- og regelverk også benyttes mer aktivt for å gi forutsigbare rammer for utviklingen.

Innspillene viser at det er noen utfordringer på lovområdet, og at det kan være behov for å endre lovverk. Hver sektor har spisskompetanse innenfor sitt område, og mye av lovverket er nettopp sektorspesifikt. Et samarbeid på tvers kan likevel være hensiktsmessig for å oppnå felles tilnærming. I noen tilfeller kan løsningen være “myke lover” i form av politiske føringer, retningslinjer, kontrakter og bruk av lisenser.

=== Konfidensialitet

Hovedregelen er at informasjon offentlige virksomheter behandler, er offentlig. Dette er både grunnlovsfestet og hovedregel i offentleglova, jf. https://lovdata.no/lov/1814-05-17-nn/§100[grunnlova § 100], 5. ledd og https://lovdata.no/lov/2006-05-19-16/§3[offentleglova § 3]. Målet er blant annet å legge til rette for at offentlig virksomhet er åpen og gjennomsiktig, og legge til rette for viderebruk av offentlig informasjon, jf. https://lovdata.no/lov/2006-05-19-16/§1[offentleglova § 1].

Mange peker på personvern som en særlig problemstilling. Vi har valgt og sette det inn i et bredere perspektiv om konfidensialitet som er forankret i https://lovdata.no/dokument/NL/lov/2006-05-19-16#KAPITTEL_3[unntaksbestemmelsene i offentleglova kapittel 3 ]og innebærer mer enn personvern.

Konfidensialitet er viktig, men kun relevant for informasjon som er underlagt lovpålagt taushetsplikt eller er unntatt offentlighet etter offentleglova av andre begrunnede årsaker.

Det er nødvendig å forstå hva konfidensialitet i offentlig sektor handler om, og hva vi skal bruke ressurser på å ivareta og dele. Ellers kan vi bryte både grunnlova og offentleglova og hindre den tilgjengeligheten disse er opptatt av.

Behovet for konfidensialitet gjelder store deler av offentlig sektor og ikke minst de 5 prioriterte sektorene. Det kan være krevende å finne balansen mellom hva som kan publiseres og hva som bør eller skal skjermes, spesielt ved muligheter for sammenstilling med andre datasett. Data må gjerne anonymiseres og aggregeres, eller virksomheten må fremstille egne versjoner som er vasket for konfidensiell informasjon. Dette krever kompetanse, kapasitet, rutiner og verktøy.

=== Finansiering og insentiver

Finansiering og manglende insentiver for deling er en utfordring i flere sektorer. Egenskapene ved åpne data og datadeling generelt gjør at kostnadene gjerne ligger hos utgiver og effektene hos brukerne, ettersom “samfunnsøkonomisk verdi” ikke kan føres som inntekt i virksomhetenes regnskap. Samtidig er det gevinster også for utgiveren i form av flere tilbakemeldinger ved økt bruk og dermed også økt datakvalitet.

I høringsutkastet til geodatastrategi er det et uttalt mål at større deler av datainnholdet i infrastrukturen blir gjort fritt tilgjengelig og gratis for brukerne. Utfordringen med å gjennomføre det, og samtidig sikre finansiering til forvaltning av detaljerte data er imidlertid ikke løst.

Selv om sektoren har gjort store fremskritt og tilbyr mer gratis data enn noen gang, er det fortsatt en vei å gå på dette området. Dette gjelder spesielt eiendomsdata. Trolig er effekten av avgifter at aktører som alt er etablerte i markedet (og som kan ta kostnadene ved kjøp av data), beholder sin posisjon i markedet på bekostning av små og disruptive aktører. Dette kan i så fall ses som en indikasjon på at markedet ikke fungerer optimalt.

Også forskningssektoren peker på behov for finansiering og insentiver. Mange av de norske infrastrukturene for forskningsdata er bygget opp gjennom kortsiktig/prosjektbasert finansiering fra Norges forskningsråd, og er primært rettet mot selve etablering av arkiv. Finansiering og plan for videre drift med hensyn til kuratering av dataene, standardisering, sikring av gode metadata, tjenester for forskerne osv. oppleves som usikker og uforutsigbar for en del av dem som leder disse infrastrukturene.

=== Hverken data eller brukere liker skillelinjer

Data i en offentlig virksomhet kan ha stor betydning for berikelse av data i en annen virksomhet. Dette gjelder også på tvers av sektorer. Et opplagt eksempel er kulturdata sammenstilt med kart- og eiendomsdata. Også andre registerdata vil kunne sammenstilles med data fra andre sektorer på måter som vil virke gjensidig berikende.

Det er derfor av betydning at de sektorvise strategiene ikke sementerer sektorvise løsninger på måter som er uheldig for datakvalitet, effektivitet og ikke minst brukerne av data.

=== Mangelfulle måleindikatorer

Difi måler i dag utviklingen knyttet til tilgjengeliggjøring av åpne offentlige data i antall datasett og antall virksomheter som tilbyr åpne data. Ettersom vi ikke har oversikt over hvilke datasett offentlige virksomheter faktisk forvalter, kan vi heller ikke si så mye om gapet mellom det som er tilgjengeliggjort i dag, og det faktiske potensialet i de fem sektorene.

Selv om indikatorene sier _noe_ om utviklingen knyttet til tilgang til data, sier de ingenting om data faktisk blir brukt og effektene av dette.

Mangelfulle måleindikatorer for tilgjengeliggjøring og bruk av offentlige data, er også et gjennomgående problem internasjonalt. Norges vektlegging av tilgang via sentrale systemer gjennom API-er gjør dessuten at hele datasett-konseptet utfordres. Hvordan man teller datasett i generiske API-er som SSBs statistikkbank, Staten vegvesens nasjonale veidatabank (http://www.vegvesen.no/fag/teknologi/Nasjonal+vegdatabank[NVDB]) eller Kulturådets http://norvegiana.no/[Norvegiana-løsning], innebærer skjønn. Antall tilgjengelige datasett kan derfor være en usikker indikator for å si noe om status og utvikling.

Gode måleindikatorer er nødvendig for en bedre nullpunktsmåling av status for de fem sektorene. Difi vurderer nye måleindikatorer på området.

=== Åpne data i en datadrevet økonomi

Tilgang på åpne data spiller en viktig rolle i en datadrevet økonomi, og det er regjeringens mål at mest mulig av de datasettene som er egnet for viderebruk, er tilgjengelig som åpne data.

Realisering av verdiene vil først bli maksimert når vi har etablert en datadrevet økonomi. Dette er avhengig av en rekke faktorer, og EU-kommisjonen peker på mange av disse i sin dataverdikjede-strategi. Her peker de på nødvendigheten av å

 * stimulere forskning og innovasjon rundt data
 * etablere gode rammeverk
 * ha en gunstig politikk- og lovutforming
 * pleie et helhetlig europeisk økosystem for data

Et velfungerende økosystem for data vil ifølge EU-kommisjonen ha følgende aktører og funksjoner:

 * Et godt samarbeid mellom universiteter / offentlige forskningsinstitusjoner og private partnere om forskning og utvikling.
 * Et tilstrekkelig antall kvalifiserte “data-arbeidere”.
 * En symbiose mellom større bedrifter og små og mellomstore bedrifter (SMB), der SMB-er utfører spesialiserte forsknings- og utviklingsoppgaver, og hvor de større bedriftene støtter oppstart og utvikling av SMB-er ved å gi dem muligheter.
 * En konstant investeringsflyt mot nyetableringer og voksende bedrifter som er aktive innenfor datateknologi og digital tjenesteutvikling.
 * Offentlige organisasjoner som fungerer som "oppstartskunder" for nye datatjenester
 * Stor tilgang på gjenbrukbare og maskinlesbare data som kan være et grunnlag for ny aktivitet og testing, samt et miljø der utviklere deler tilbake sine vaskede og integrerte data for videre bruk.
 * En solid infrastruktur, basert på raskt internett og datalagringstjenester, herunder infrastruktur for å støtte datadrevet forskning og utvikling.

Norge har flere av disse funksjonene på plass, men vi kan trolig gjøre mer for å sette disse bitene sammen til en helhetlig politikk.

EU-kommisjonen peker i sin dataverdikjede-strategi på behovet for en markedsplass der utviklere kan dele sine vaskede og integrerte data. https://data.norge.no[Data.norge.no] dekker i dag behovet for å synliggjøre offentlige virksomheters åpne datasett, men det finnes ingen tilsvarende tjeneste for aktører høyere oppe i dataverdikjeden. Kundene i et marked der næringslivet tilbyr bearbeidede offentlige data kan være både privat og offentlig sektor.

=== Oppsummering

 * På tross av en stadig økning i tilgang på åpne offentlige data, synker Norge på internasjonale indekser. Dette skyldes først og fremst at andre land gjør mer enn oss.
 * Vi vet lite om effektene av økt tilgang til offentlige data i Norge. Dette kan ses som et hinder for mer tilgjengeliggjøring
 * Velfungerende økosystemer rundt offentlige data er viktig for å hente ut gevinster av økt tilgang på data.
 * Vilkår for deling av data er ikke alltid vurdert ved etablering av sentraliserte systemer med data fra flere aktører.
 * Ved privatisering av funksjoner og overføring av forvaltningsansvar til stiftelser og virksomheter som er unntatt offentlighet, må behovet for tilgang til data vi regner som offentlige, ivaretas.
 * Både privat og offentlig sektor har behov for økt kompetanse knytt til bruk av data i årene som kommer.
 * Felles spesifikasjoner og standarder blir viktig for å kunne utveksle data og metadata på tvers av fagområder og sektorer, samtidig som domenespesifikke og internasjonale behov må ivaretas.
 * Det kan være krevende å finne balansen mellom hva som kan publiseres og hva som bør eller skal skjermes. Behovet for konfidensialitet gjelder store deler av offentlig sektor og ikke minst de 5 prioriterte sektorene.
 * Finansiering og manglende insentiver for deling av data er en utfordring i flere sektorer. Utgiftene kommer andre steder enn gevinstene.
 * Innsamling og forvaltning av detaljerte kart- og eiendomsdata finansieres til dels ved hjelp av avgifter. Dilemmaet mellom finansiering og ønsket om gratis data er ikke løst.
 * Data brukes på tvers av sektorer og fagområdet i økende grad. Sektorvise strategier må ikke sementere løsninger som er uheldig for datakvalitet, effektivitet og ikke minst brukerne av data.
 * Vi har i dag mangelfulle indikatorer for å måle status for tilgang til data fra de fem sektorene.
 * Tilgang på åpne data kommer til å spille en større rolle fremover i en stadig mer datadrevet økonomi.
