== Forskning

=== Pågående aktiviteter

Kunnskapsdepartementet (KD) har bedt Forskningsrådet om å bistå i arbeidet med å utarbeide en nasjonal strategi/handlingsplan for tilgjengeliggjøring av forskningsdata. I januar 2017 vil Forskningsrådet levere et kunnskapsgrunnlag som inneholder

 * Kartlegging av Forskningsrådets investeringer i infrastrukturer som støtter tilgjengeliggjøring av forskningsdata
 * Kartlegging av hvilke norske tjenester for lagring av forskningsdata som finnes i dag
 * Innspill til arbeidsdeling og rolleavklaring mellom tjenesteleverandører
 * Innspill til mulige finansieringsmodeller for nasjonalt viktige tjenester knyttet til lagring og deling av forskningsdata

De to første punktene har bakgrunn i at KD, gjennom bevilgninger til Forskningsrådet, har investert 4,1 mrd. i forskningsinfrastruktur siden 2009. Av disse har én mrd. gått til et tjuetalls infrastrukturer for å håndtere og tilgjengeliggjøre data. Andre departementer investerer også tungt forvaltningsmessig i datahåndtering, registre osv.

Med utgangspunkt i kunnskapsgrunnlaget fra Forskningsrådet med mer, vil KD begynne det tverrdepartementale arbeidet med en strategi for forskertilgang til data i januar 2017.

Andre norske aktiviteter som er relevant for tilgjengeliggjøring av forskningsdata:
 * KD mottok forslag til nasjonale retningslinjer for åpen tilgang til forskningsresultater fra arbeidsgruppe 14. juni. Forslaget har vært på høring, fristen var 1. november. Current Research Information System in Norway (CRIStin) bistår i oppsummeringen av høringssvarene og vil arrangere en konferanse om aktuelle problemstillinger i januar 2017.
 * Helse- og omsorgsdepartementet (HOD) ferdigstilte sin internrapport om Nasjonal helseregisterstrategi – status, utfordringer og veien videre 30. august.
 * Agenda Kaupang leverer sin rapport til Forskningsrådet (NFR) om "Persondata til helseforskning" 15. desember 2016 (hovedtrekk ble gjort kjent på et arrangement 8. november).
 * Arbeidsgruppen for IKT-strategi og helhetlige løsninger i UH leverte første delrapport til KD 29. juni og vil levere endelig rapport med forslag til IKT-strategi for UH-sektoren i november-desember. Spørsmålet om IKT-organisering utgjør en viktig komponent i oppfølgingen av rapporten fra Gjedrem og Fagernæs, "Kunnskapssektoren sett utenfra" (jan. 2016), om organisering av kunnskapssektoren.
 * HOD mottar rapporten fra ekspertutvalget som skal utrede enklere tilgang og bedre utnyttelse av helsedata 30. juni 2017.
 * Norge har formannskapet i Nordisk ministerråd i 2017. Åpen forskning vil være et prioritert felt i det norske formannskapet.
 * FIN har nedsatt et utvalg som skal vurdere statistikkloven og Statistisk sentralbyrås virksomhet. Utvalget skal levere sin rapport innen 15. desember 2017. https://www.regjeringen.no/no/aktuelt/dep/fin/pressemeldinger/2016/utvalg-skal-vurdere-statistikkloven/mandat-for-statistikklovutvalget/id2510801/
 * EUs nye personvernforordning skal implementeres i Norge våren 2018. JD leder arbeidsgruppen der også KD deltar.

Tilgjengeliggjøring av forskningsdata er et viktig tema også globalt, og spesielt EU har mange aktiviteter som skal støtte opp under bedre tilgang, bruk og deling av forskningsdata. Noen sentrale, pågående aktiviteter:

 * EU vedtok ambisiøse rådskonklusjoner om åpen forskning 27. mai 2016. Punkter på European Research Area Roadmap om tilgang til kunnskap skal følges opp (http://ec.europa.eu/research/era/optimal-circulation_en.htm), jf. vårt nasjonale veikart prioritering 5 A og B https://www.regjeringen.no/contentassets/1b619466970f4e9b98b3d639b78cd200/era-national-action-plans-2016---2020---norway.pdf
 * Europakommisjonen har besluttet at alle data som genereres gjennom forsknings- og innovasjonsprogrammet Horisont 2020 skal være åpne som standard (as open as possible, as closed as necessary). Dette var en del av European Cloud Initiative, presentert 19. april 2016.
 * Som en del av European Cloud Initiative presenterte kommisjonen 19.april 2016 også planene om en European Open Science Cloud (EOSC).  EOSC skal sikre tilgang til data og tilhørende tjenester basert på FAIR prinsippene; Findability, Accessibility, Interoperability, Reusability. EOSC vil bli basert på eksisterende komponenter som er utviklet gjennom europeisk samarbeid eller i medlemslandene og assosierte land.
 * OECD Global Science Forum har to pågående prosjekter knyttet til åpne forskningsdata; Sustainable business models for data repositories og International coordination of data infrastructures for open science. (Norske representanter er henholdsvis Roar Skålin, Forskningsrådet, i den første og Benjamin Pfeil, UiB/Bjerknessenteret, i den andre.)
 * Den 14. september 2016 presenterte Europakommisjonen forslag til nytt opphavsrettsdirektiv. Direktivet er relevant for forskningsdata fordi det omtaler forskernes mulighet til å søke i tekst og data (text and data mining). https://ec.europa.eu/digital-single-market/en/news/proposal-directive-european-parliament-and-council-copyright-digital-single-market
 * I Frankrike er det vedtatt en egen lov om åpen tilgang til forskningsresultater, herunder forskningsdata. https://www.openaire.eu/france-final-text-of-the-law-for-oa-has-been-adopted
=== Sentrale problemstillinger

Noen problemstillinger som vi antar vil bli sentrale i arbeidet med å utforme en strategi for å gjøre forskningsdata tilgjengelig er:

*Finansiering av arkiver for forskningsdata:* Løsningene for arkivering av forskningsdata må ha en langsiktighet for at de skal være attraktive. Dette er en forutsetning både for de som deler data og de som bruker dataene. Det er også et krav som stilles både av de som finansierer forskning og tidsskriftene som publiserer resultatene av forskning. Mange av de norske infrastrukturene for forskningsdata er bygget opp gjennom kortsiktig/prosjektbasert finansiering fra NFR som primært er rettet mot selve etableringen av arkivet. Finansiering og plan for videre drift mht. kuratering av dataene, standardisering, sikring av gode metadata, tjenester for forskerne osv. oppleves som usikker og uforutsigbar for en del av dem som leder disse infrastrukturene.  +
*Finansiering av tilgang til arkiver opprettet for forvaltningsformål:* Forskningen bruker flere databaser og registre som er opprettet for forvaltningsformål. Eierne av disse databasene/registrene har ikke egen bevilgning eller andre midler for å tilgjengeliggjøre data for forskning. I noen tilfeller må brukerne dekke alle kostnadene ved tilgang. Det kan redusere bruk av dataene i forskning og påvirke hvilken forskning som kan gjennomføres. +
*Bruk av helsedata i forskning:* (forutsetningen om at personvern ivaretas er selvsagt): Dagens situasjon er preget av mange aktører med databehandleransvar som er underlagt ulike forskrifter og formål og hvor komplekse og strenge utleveringsbetingelser vanskeliggjør eller umuliggjør gjenbruk av data. De ulike datasystemene har ulik kvalitet, formater, standarder og grensesnitt som fører til utfordringer vedrørende muligheten for å koble datasett fra ulike databehandlere. Forskerne opplever i dag lite forutsigbarhet mht. tidsbruk og kostnader ved søknad om tilgang til data. Det er ønske om en gjennomgang av de ulike registres forskrifter og omforent tolkning av forskriftene for å lette tilgangen og gjenbruk av data, en effektivisering av tekniske løsninger, mer opplæring av forskerne samt en større forutsigbarhet for forskerne vedrørende søknader om tilgang til data, uten at dette forringer ivaretakelsen av personvernet. +
*Insentiver for publisering og deling av data:* Sett fra forskerens synspunkt er det i dag få insentiver knyttet til å dele data, mens arbeidet med å gjøre data tilgjengelig og brukbare for andre forskere kan være omfattende og gå utover egen vitenskapelig produksjon. +
*Harmonisering med internasjonale løsninger:* Deling av forskningsdata er en internasjonal aktivitet. Det betyr at for eksempel finansieringsmodeller, tekniske løsninger for tilgang (autentisering og autorisering), metadata, lisenser og identifikatorer for datasett må være basert på eller tilpasset internasjonale løsninger. Videre vil forskerne benytte både institusjonelle, nasjonale og internasjonale arkiv for deling av sine data.  +
*Dataomfang:* Det produseres enorme mengder med forskningsdata. Det vil ikke være kostnadseffektiv å gjøre alle dataene tilgjengelig, ei heller å lagre dataene. Det må utvikles retningslinjer for å avklare hvilke data som skal tas vare på og gjøres tilgjengelig.
